### PR TITLE
Handle malformed dumpsys package output.

### LINKED ISSUE #1077: Tracing fails to start on Xiaomi 12
**Environment information:**
 - AGI version: 2022-3.0.0
 - Host OS: Windows
 - Device model: Xiaomi 12 Global
 - Android Version: A12, latest available

**Bug description**
Attempting to system trace any debuggable app, even the builtin agi sample fails.

**Reproduction steps**
Attempt to trace any app, it will fail

**Stacktrace**
```
com.google.gapid.server.Client$InternalServerErrorException: Tracing Failed
   Cause: Could not start trace
   Cause: Cannot trace non-debuggable app
   Cause: Device is not a userdebug build

	at com.google.gapid.server.Client.throwIfError(Client.java:327)

	at com.google.gapid.server.Client.lambda$streamTrace$58(Client.java:301)

	at com.google.gapid.server.GapidClientGrpc$StreamHandler.onNext(GapidClientGrpc.java:232)

	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:465)

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:656)

	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:641)

	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)

	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

Caused by: com.google.gapid.server.Client$Stack: For request: RPC->streamTrace()

	at com.google.gapid.server.Client.streamTrace(Client.java:298)

	at com.google.gapid.server.Tracer.trace(Tracer.java:41)

	at com.google.gapid.views.TracerDialog.showTracingDialog(TracerDialog.java:197)

	at com.google.gapid.views.TracerDialog.showSystemTracingDialog(TracerDialog.java:175)

	at com.google.gapid.LoadingScreen.lambda$new$0(LoadingScreen.java:117)

	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)

	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4237)

	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)

	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4054)

	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3626)

	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)

	at org.eclipse.jface.window.Window.open(Window.java:799)

	at com.google.gapid.Main$UI.show(Main.java:140)

	at com.google.gapid.Main.main(Main.java:80)

```
**Screenshots**
image

**Additional debugging information**
[gapic.log](https://github.com/google/agi/files/8447290/gapic.log)
[gapis.log](https://github.com/google/agi/files/8447291/gapis.log)
[logcat-full.txt](https://github.com/google/agi/files/8447326/logcat-full.txt)

### PR DESCRIPTION
**Pull request by pmuetschard**
Some devices produce malformed `dumpsys package` output, adding in extra newlines. This change handles a specific version of how this extra whitespace breaks the parser.

Parsing the output of `dumpsys package` is not really a good way to do this. Fixing this in a better way is tracked in http://b/229287771

Fixes #1077

### CODE REVIEW

File: core/os/android/adb/adb_data_test.go [hunk 1]
```diff
@@ -95,7 +95,10 @@ Activity Resolver Table:
 Packages:
   Package [com.google.foo] (ffffffc):
     userId=12345
-    primaryCpuAbi=armeabi-v7a
+    *** extra whitespace on next line is for testig https://github.com/google/agi/issues/1077 ***
```
Comment (ttanatb) [inline core/os/android/adb/adb_data_test.go:98]: testing

**Review by ttanatb — APPROVED** [review]
