### PR TITLE
Fixes an issue with MEC resources' creation command reference.

### LINKED ISSUE #1074: java.lang.NullPointerException at com.google.gapid.views.PipelineView.lambda$createPipelineTabs$4(PipelineView.java:272)
**Environment information:**
 - AGI version: agi-3.0.0
 - Host OS: macos catalina 10.15.5 (19F101)
 If tracing on Android:
 - Device model: Google Pixel 4 XL
 - Android Version: Android 12

**Bug description**
Report "The application encountered an error:Unhandled exception in the UI thread." Error on Performance pane 

**Reproduction steps**
1. Capture trace
2. Configure Device and Type  and select Frame Profile - OpenGL on ANGLE
3. Choose the opengl demo app
4. Select Manual under Start and Duration section
5. Configure Ouput as needed
6. Click ok  - start -stop to get profile
7. Select Performance pane and click command below RenderPass
8. Error dialog with stack trace shows

**Stacktrace**
The application encountered an error: Unhandled exception in the UI thread.
java.lang.NullPointerException
	at com.google.gapid.views.PipelineView.lambda$createPipelineTabs$4(PipelineView.java:272)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
	at org.eclipse.swt.widgets.Control.drawWidget(Control.java:1270)
	at org.eclipse.swt.widgets.Button.drawWidget(Button.java:547)
	at org.eclipse.swt.widgets.Widget.drawRect(Widget.java:776)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6124)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationNextEventMatchingMask(Display.java:5398)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5802)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.nextEventMatchingMask(NSApplication.java:92)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3877)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:67)
	at com.google.gapid.views.ErrorDialog.showErrorDialog(ErrorDialog.java:59)
	at com.google.gapid.Main$UI.lambda$registerWindowExceptionHandler$0(Main.java:133)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at com.google.gapid.Main$UI.show(Main.java:140)
	at com.google.gapid.Main.main(Main.java:80)
**Screenshots**
AndroidGpuInspectorError
**Additional debugging information**
code snippet from PipelineView.java
`
stageButton.addListener(SWT.Paint, e -> {
    Rectangle areaSize = stageButton.getBounds();
    e.gc.setLineWidth((int)(areaSize.height * 0.1));
    if (hoveredButton == stageButton || stageMap.get(selectedStage).stageButton == stageButton) {
        e.gc.setForeground(getDisplay().getSystemColor(SWT.COLOR_BLUE));
    } else {
        e.gc.setBackground(getDisplay().getSystemColor(SWT.COLOR_LIST_FOREGROUND));
    }
    e.gc.drawPolygon(new int[] {0, 0, areaSize.width - 1, 0, areaSize.width - 1, areaSize.height - 1, 0, areaSize.height - 1});
});
`
gfxtrace file with error reported above.
[error_angle_20220406_2140.gfxtrace.zip](https://github.com/google/agi/files/8440299/error_angle_20220406_2140.gfxtrace.zip)

### PR DESCRIPTION
**Pull request by pmuetschard**
We track at what command resources are created. Resources created before the trace (in the MEC state) do not have a "creation command". In the past they were associated with the first command in the trace, which has caused some minor reporting type problems, but also later on a crash. This was partially fixed in 21f0184, but together with e313301 caused a
regression in the pipeline view, which now was no longer properly referring to shader resources due to the now negative creation reference.

Fixes #1074
Bug: http://b/229387566

### CODE REVIEW

File: gapic/src/main/com/google/gapid/views/ShaderView.java [hunk 1]
```diff
@@ -123,7 +123,7 @@ public static class ShaderWidget extends Composite {
     private final TabFolder tabFolder;
     private final Composite sourceContainer;
     private final Group statGroup;
-    private final TableViewer statTable;
+    protected final TableViewer statTable;
```
Comment (mikes-lunarg) [inline gapic/src/main/com/google/gapid/views/ShaderView.java:126]: Why did this need to change?

Comment (pmuetschard) [reply gapic/src/main/com/google/gapid/views/ShaderView.java:126]: It's referenced from within an inner class. Inner classes are a language thing, but not a JVM thing, so the compiler has to add a getter function so the inner class can get access to the field. Making it protected avoids that.

**Review by yalcinmelihyasin — APPROVED** [review]
