### PR TITLE
Fix display of representations for OpenGL draw commands/groups

### LINKED ISSUE #669: Frame capture: 1-draw-call difference in images between glDrawElements and vkCmdDrawIndexed
Note: This is described w.r.t. FIFA Soccer, but is true for all GLES games/applications.

Describe the issue:

- This may be an issue with other games, but I just noticed it.
- Looking at my frame capture of FIFA Soccer, I sometimes click on the a higher-level glDrawElements node, and sometimes I click on the GLES and/or Vulkan nodes underneath. For the same higher-level glDrawElements, I get different images for the GLES and Vulkan nodes.

Expected behavior:

- When I open and select different nodes of a frame capture of a GLES app, I expect the same image to be seen regardless of whether I am clicking on the GLES or Vulkan nodes

Actual behavior:

- I am seeing one-draw-call difference between the "OpenGL ES Commands" and the "DrawIndexed" hierarchies. Since a small thumbnail is included on some of the hierarchy, I started looking at the draws before and after big changes. That's when I noticed this.

Repro steps:

- With the capture that I point to (below), look at when the draws in the 2nd RenderPass change from black to green. Here's what the hierarchy looks like:
  - Host Coordination
  - vkQueueSubmit
    - pSubmits[0]
      - Command Buffer
        - Render Pass
        - Render Pass
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
          - glDrawElements
            - vkCmdBeginDebugUtilsLabelEXT
              - OpenGL ES Commands
                - vkCmdBeginDebugUtilsLabelEXT
                - gl*
                - ...
                - glDrawElements
                - vkCmdEndDebugUtilsLabelEXT
              - DrawIndexed
                - vkCmdBindPipeline
                - ...
                - vkCmdDrawIndexed
              - vkCmdEndDebugUtilsLabelEXT
            - glDrawElements
              - vkCmdBeginDebugUtilsLabelEXT
              - OpenGL ES Commands
                - vkCmdBeginDebugUtilsLabelEXT
                - gl*
                - ...
                - glDrawElements
                - vkCmdEndDebugUtilsLabelEXT
              - DrawIndexed
                - vkCmdBindPipeline
                - ...
                - vkCmdDrawIndexed
              - vkCmdEndDebugUtilsLabelEXT
            - glDrawElements
            - ...

- I chose those particular parts of the hierarchy because that's where the green soccer field first gets drawn.
- If you open up the "OpenGL ES Commands" and the "DrawIndexed" nodes above, and click on the lower-level glDrawElements and vkCmdDrawIndexed nodes. You will see that the GLES draw doesn't show the same image as the Vulkan draw.

Versions:

- AGI: v1.1.0-dev-20210110
- ANGLE (pre-built): <ANGLE version doesn't matter>
- App version: versionCode=754 minSdk=23 targetSdk=29

### PR DESCRIPTION
**Pull request by mark-lunarg**
In an ANGLE AGI trace, the thumbnail/resources of the containing OpenGL group and the OpenGL drawcall displayed out-of-date
data. Updated these representations at query-time to reflect the correct Vulkan state.

Passed presubmit tests.

Fixes #669

### CODE REVIEW

**Comment by mark-lunarg** [comment]
@googlebot I signed it!

File: gapis/resolve/command_tree.go [hunk 1]
```diff
@@ -236,8 +243,11 @@ func (r *CommandTreeResolvable) Resolve(ctx context.Context) (interface{}, error
 			return fmt.Errorf("Fail to mutate command %v: %v", cmd, err)
 		}
 		if filter(id, cmd, s, api.SubCmdIdx([]uint64{uint64(id)})) {
+			var groupnum int
```
Comment (pmuetschard) [inline gapis/resolve/command_tree.go:246]: `groupnum` doesn't appear to be used anywhere.

File: gapis/resolve/command_tree.go [hunk 2]
```diff
@@ -546,3 +557,28 @@ func setRepresentations(ctx context.Context, g *api.CmdIDGroup, drawOrClearCmds
...
+	aliasRepId := api.CmdNoID
+	if item.Name == "OpenGL ES Commands" {
+		parentIndices := indices[:len(indices)-1]
+		pItem, _ := cmdTree.index(parentIndices)
+		parentItem := pItem.(api.CmdIDGroup)
+		aliasRepId = parentItem.Range.Last()
+	} else if strings.HasPrefix(item.Name, "glDraw") || strings.HasPrefix(item.Name, "glMultiDraw") {
+		pindices := indices[:len(indices)-1]
+		pItem, _ := cmdTree.index(pindices)
+		switch parentItem := pItem.(type) {
```
Comment (pmuetschard) [inline gapis/resolve/command_tree.go:571]: Since you only have one case statement, I think it's better to do:
```
if parentItem, ok := pItem.(api.CmdIDGroup); ok {
...
}
```
Same below.

File: gapis/resolve/command_tree.go (hunk 1 above)
Comment (mark-lunarg) [reply gapis/resolve/command_tree.go]: Leftover instrumentation, sorry.

File: gapis/resolve/command_tree.go (hunk 2 above)
Comment (mark-lunarg) [reply gapis/resolve/command_tree.go]: Thanks -- was looking for something like this!

**Review by pmuetschard — APPROVED** [review]
